### ISSUE TITLE
Components returning nil

### ISSUE THREAD

**Issue by jimrthy** [stuartsierra/component#17]
This is probably a documentation thing (at most).

I recently restructured one of my projects from the "workflow reloaded" style, and I made a couple of breaking changes that left me baffled for quite a while.

The real problems were that one of my components' ctors was returning nil, while another was returning nil from (start).

The error message I got in both cases (after I worked my way through the system tree) was that a required component is missing. It also told me which component was the problem, and which component required it (although which was what wasn't clear for a while).

After I actually looked at the code and realized that the problem wasn't so much that they were disappearing but just that nil values weren't allowed, it was pretty easy to sort out.

There's something that was catching the exception before my actual call to reset/refresh. I don't know  where to even start looking for that, but I seriously doubt it's here.

Anyway. This really seems like a very minor nit in a really great library. Thank you!

**Comment by stuartsierra** [comment]
Possible resolution on [check-nils](https://github.com/stuartsierra/component/tree/check-nils) branch currently at 61dbd88e32c2f819a24c5fb3d4374db709834fe1

**Comment by stuartsierra** [comment]
On further reflection, I don't want to prohibit start/stop from returning nil. There are legitimate use cases for that, such as a component that wishes to remove itself from the system after starting. But I may still be able to throw a different error message when a dependency is nil versus when the key is missing.

**Comment by stuartsierra** [comment]
A less-restrictive possibility on the [nil-error branch](https://github.com/stuartsierra/component/tree/nil-error) currently at fb891500506b048bd8d9d689dfd3ed8c0e940944 — return a specific error message for the case when a component's value is `nil`, and suggest the probable cause in the error message.

**Comment by stuartsierra** [comment]
I have applied the error-message change from fb891500506b048bd8d9d689dfd3ed8c0e940944 in release version 0.2.4.

**Comment by jimrthy** [comment]
I know that this is a day late and a dollar short. But, FWIW, this works great for me. Thank you!
