### ISSUE TITLE
component self reflection

### ISSUE THREAD

**Issue by hiredman** [stuartsierra/component#22]
it would be nice if when running something over a system via update-system, a component could know its "name" in the system.

 I am working on some code that uses component internally to organize things, and it operates off a distributed job queue type thing. the first step when it pulls a job is to sort of route it back in to the nice component world, because each job tells you the "name" of the component it is destined for. I have some generic behavior I would like to capture in a component (and of course have component wire in different dependencies to specify the behavior for different cases), when this behavior includes the component publishing work that should be routed to itself, this is challenging because the component doesn't know what name that specific instance of the generic component will have in the system.

it seems like a dynamic binding of the key in update-system would work well

**Comment by stuartsierra** [comment]
It is a goal of mine that a component should never need to know anything about the system of which it is a part, and that code should never have to "reach through" the system to get at a component. See also my comments on [#18](https://github.com/stuartsierra/component/issues/18#issuecomment-68563228).

What you're describing sounds like a specialized way to construct a system. If you want to tell a component its name, just assoc it. Something like this should work:

```clojure
(defn assoc-component-names
  "Assocs :system-key <key> into each component in the system, where
  <key> is the location of the component within the system. Call this
  before start."
  [system]
  (reduce (fn [system key]
            (assoc-in system [key :system-key] key))
    system
    (keys system)))
```
