### ISSUE TITLE
wondering the reasons to choose defrecord vs reify in stuartsierra/component

### ISSUE THREAD

**Issue by tangrammer** [stuartsierra/component#29]
Hi guys, 
I'm just wondering the pros/contras that justify to choose defrecord vs reify as component fn constructor.

in the component README we can read 
"To create a component, define a Clojure record that implements the Lifecycle protocol."

Yes I know that "defrecord creates an immutable persistent map which implements a protocol." but I think that the same thing can be achieved with reify (BTW: "om" way to define component) over a persistent map... 

Do you think there are more reasons to set defrecord as default base fn for components?

Thanks in advance
Juan

**Comment by stuartsierra** [comment]
Answered on the Clojure mailing list:
https://groups.google.com/d/topic/clojure/xqU_JSFWK-k/discussion
