### ISSUE TITLE
Clojurescript support

### ISSUE THREAD

**Issue by ToBeReplaced** [stuartsierra/component#3]
Is there any interest in supporting clojurescript down the line?  I know we are in alpha mode.  Still, this would be very useful for interactive development on the client side.

The only current incompatibilities as far as I can tell are the `java.lang.Object` no-op implementation and the use of `Long/MAX_VALUE` in `com.stuartsierra/dependency`.

If there is interest, what is your preferred method of separating out the portable code from the non-portable code and packaging releases?

**Comment by timgilbert** [comment]
I'm just leaving this comment here in case others come to this ticket through a search for "clojurescript stuartsierra component", as I did. There is a [clojurescript fork of component available](https://github.com/quile/component-cljs) which has been kept reasonably up to date as I write this. In addition, the [leaven library](https://github.com/palletops/leaven) is a similar project which has clojurescript compatibility as one of its central goals.

Also, the Jira ticket tracking the feature-expressions language feature that Stuart mentions in his comment above is [CLJ-1424](http://dev.clojure.org/jira/browse/CLJ-1424), in case anyone is curious.

**Comment by JulianLeviston** [comment]
@timgilbert thanks, I guess... however, reasonably up to date is a bit of a misnomer, given neither this work that I made a stab at, and then the fork that quile subsequently made months and months later on the same version of component haven't been updated any more recently than each other. There are additional changes to stuart's component that haven't been tracked by either of us.

But yes, good to mention them both here as I have no interest in keeping up maintenance of this beyond what I've already done.

**Comment by metasoarous** [comment]
So... there are proper reader conditionals now. Any chance of reopening this issue?

**Comment by maseb** [comment]
@metasoarous That would certainly make me a happy camper.

**Comment by stuartsierra** [comment]
ClojureScript support added in release 0.3.0

**Comment by metasoarous** [comment]
Wonderful!

On Sat, Sep 19, 2015, 3:59 AM Stuart Sierra <notifications@github.com>
wrote:

> ClojureScript support added in release 0.3.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stuartsierra/component/issues/3#issuecomment-141567212>
> .
>
-- 

Chris

Sent via mobile
