### ISSUE TITLE
Type changes checks to prevent dissoc accidents?

### ISSUE THREAD

**Issue by jeroenvandijk** [stuartsierra/component#30]
Hi Stuart,

Thanks for this library, the concept and the library itself have been of great help to us.

As mentioned by README `dissoc` shouldn't be used on component records as it will change the record into a map. It is easy to forget to tell this to new component users or just to forget it in general though. This results in very unexpected results sometimes. As far as I know a component should never "change" types during a start/stop cycle. Do you think it would make sense to add assertions for unexpected type  changes after stop and start? This would catch the `dissoc` accidents I believe.

Cheers,
Jeroen

**Comment by stuartsierra** [comment]
I have never had any reason for a component to change its type after `start`, but there is nothing about 'component' which depends on this. It is possible that someone will come up with a use case for component records that return different types from `start`. It would be an artificial limitation on the power of 'component' to forbid this.
