### ISSUE TITLE
Allow Sequential collections to be used in component/using

### ISSUE THREAD

**Issue by mpenet** [stuartsierra/component#31]
Hi Stuart,

When building the list of dependencies for `using` dynamically we would often end up with a Sequential of some kind, right now there is a `vector?` check that will force the user to call vec/into [] prior to passing the dependencies to the function. I can't seem to find a reason not to allow other Sequentials. 
You have a OR here with the necessary change to make it work: https://github.com/stuartsierra/component/pull/27

**Comment by stuartsierra** [comment]
See #27
