### ISSUE TITLE
still dependent on IoC container?

### ISSUE THREAD

**Issue by aft-luke** [stuartsierra/component#47]
This might not be an issue, but it's something I wanted to point out from an implementer's point of view. I'm relatively new to clj, so I might be totally off the mark.

A few DI systems I've used allow total dependency swapping, including injecting a different implementation of their own self. In a typical boot process I might define a `main` file that goes something like this...

```
di-system := initializeDiSystem()
features := ['module-a', 'module-b']
features.forEach( (feature) { feature.init(di-system) }

// module-a
component := ...
expose init( di-system ) {
  di-system.registerComponent( component )
}
```

In this weird psuedo-language, the point I'm trying to make is that each module receives "some form" of a DI system, it doesn't really care which, and each module is responsible for registering itself. Is this possible with clj and `stuartsierra/component`?'

I'm trying to get away from each and every module looking like:
```
(ns app-reframe.core
  (:require [com.stuartsierra.component :as component]))

(defrecord SomeComp [args]
  component/Lifecycle

  (start [component]
    (println ";; starting")
    component)

  (stop [component]
    (println ";; stopping")
    component))
```

Which has a hard dependency on `component`, and to move to something like:

```
(defn init [di]
  (map->SomeComp {:di di }))
```

But this doesn't really seem possible given the way records must be declared at top-level and not inside a function. Also, if a record implements a lifecycle protocol I don't see a way around the top-level `:require`. 

I'm hoping someone with more experience might be able to answer this with definitiveness one way or the other. A simple "you can't do that" would suffice.

**Comment by stuartsierra** [comment]
You can’t do that. :)
