### ISSUE TITLE
How to inject db transaction per http request? 

### ISSUE THREAD

**Issue by darkleaf** [stuartsierra/component#56]
Example.
I have several db gateway components that depends from db connection component.
I have use case component that depends from gateway.
I have controller(http handler) that depends from use case.
"Depend" is a component runtime dependency, not namespace dependency.

I want to pass into gateway db transaction instead of db connect.
Db transaction will be created from original db connect per http request .

Is it possible?

**Comment by stuartsierra** [comment]
Please direct all questions to the [Clojure Mailing List](https://groups.google.com/group/clojure), where you are more likely to find someone who can provide a relevant answer.
