### ISSUE TITLE
Reloading with component *without* introducing global state

### ISSUE THREAD

**Issue by codeasone** [stuartsierra/component#58]
I'm just getting started with component, and have reached an impasse where I cannot see a way of getting the reloading benefits of `lein-ring` without introducing global state.

I've created a minimal re-production of where I have got to and was hoping to get some advise on whether what I'm aiming for is possible.

https://github.com/codeasone/component-reload-issue

I've also reached out to the `lein-ring` project: https://github.com/weavejester/lein-ring/issues/189

**Comment by stuartsierra** [comment]
Hi and thanks for your interest in Component. I recommend posting this question on the [Clojure Mailing List](https://groups.google.com/group/clojure). That is where the greatest number of people are likely to see it and be able to offer answers. You may also want to ask the question in [Clojurians Slack chat](http://clojurians.net/).
