### ISSUE TITLE
Feature request: add system key metadata to components

### ISSUE THREAD

**Issue by rafaeldff** [stuartsierra/component#61]
The available extension points are almost perfect to allow users to add their own observability to component life-cycle events. It's a simple matter of calling `(update-system)` passing a function that wraps `(component/start)` in logging statements. The only aspect missing to fully address our requirements would be a way to find the key under which the component being started is bound in the system, in order to include that information in the logging message. 

Passing the key as another argument to the `f` updating function would be a breaking change since it is documented to receive the args initially passed in. However this seems like a fine usage for clojure metadata.

Something along the lines of https://github.com/rafaeldff/component/commit/2889d5d92ceff36119d68e3fed466e30281f24db would address this issue, in my opinion (I'm not opening a pull-request now due to the contribution instructions in the repository).

**Comment by stuartsierra** [comment]
Hi, and thanks for your interest in Component!

One of the goals of the original design is that any individual component should not be aware of any details about the surrounding system, including where it is located in the system map. To add that information, even as metadata, opens up the potential for system details to leak into the component.

On most of the applications I have worked on, I have found that logging components' start/stop does not provide much useful information. If the application starts successfully, then I know that all the components started successfully. If any one component fails, then the application will not start. Either way, it is sufficient to log that the entire system started successfully or not.

That said, it is possible to add the system key to every component without modifying the behavior of `update-system`. Something like this, called after constructing the system but before `start`, should work:

```clojure
(defn add-system-keys-metadata [system]
  (reduce-kv (fn [sys k _]
               (update sys k vary-meta assoc ::system-key k))
             system
             system))
```
