### ISSUE TITLE
Non-associative components?

### ISSUE THREAD

**Issue by seancorfield** [stuartsierra/component#67]
One of [Integrant's rationale points](https://github.com/weavejester/integrant#rationale) is that "In Component, only records or maps may have dependencies".

Since 0.4.0, Component has allowed lifecycle methods to be attached to anything that can carry metadata. That means you can attach `start`/`stop` to a lot more things than just records and hash maps -- in `next.jdbc`'s Component-compatible connection pool code, that allows a function (that returns a connection pool) to have a `stop` lifecycle method that can shut down the connection pool.

The dependency information has always been metadata, but there's an inherent assumption that systems and components are _associative_ and various logic in Component just calls `get` and `assoc` on components. Hence Integrant's point above still stands, even though "anything" can have a lifecycle in Component.

Would you be interested in a Pull Request that modified Component so that non-associative components could carry dependencies in their metadata (leaving the behavior unchanged for associative components)?

**Comment by stuartsierra** [comment]
Hi @seancorfield,

I've given this a lot of thought over the past few weeks.

You can already use non-Associative objects in a Component System as long as they do not have dependencies. I've seen functions, Java objects, and core.async Channels all used as Components. You don't have to return a map/record from `Lifecycle/start` either; that's just a convention.

Components only need to be Associative when they have dependencies. The use of `assoc` for dependencies is pretty fundamental to the design. In particular, it ensures that any Component in a started System is functionally indistinguishable from a complete System. This is a useful property when combining systems.

Allowing dependencies to be passed via metadata would mean having Components which **are not** Associative but **are** metadata-compatible. That's a small set of Clojure-native types. It would not allow, for example, a Java object to be used as a Component with dependencies. It's already common to wrap Java objects in Clojure maps or Records just to get metadata capabilities, so nothing much would change there.

While I'm not totally against this in theory, I currently do not envision a significant benefit relative to the additional complexity it would introduce. If you have other use cases in mind, I would be happy to discuss them further.

Thanks for the suggestion!
–S

**Comment by seancorfield** [comment]
Thanks for the feedback and for taking the time to analyze the suggestion. I agree that it adds a non-trivial amount of complexity and I was fairly sure you wouldn't consider the benefits to be worthwhile -- but I figured it was worth raising. I don't really have a concrete use case right now -- I've always found ways to fit into Component's world view so far. I'll close this out (but feel free to reopen if you want to keep it in play for future discussion etc).
