### ISSUE TITLE
Cleaning up component dependencies by default

### ISSUE THREAD

**Issue by mthl** [stuartsierra/component#68]
Hello,

While using components for a project with an architecture built around service records, I ended up repeating the following pattern for each service record :

```clojure
(defrecord ComponentZ [config componentX componentY]
  ,,,

  component/Lifecycle
  (start [this]
    this)

  (stop [this]
    (assoc this
           :componentX nil
           :componentY nil)))
```

As I understand it, it seems possible to remove such ceremony by improving the default implementation of the `stop` function to remove the known dependencies automatically like this:

```clojure
(extend-protocol component/Lifecycle
  #?(:clj java.lang.Object :cljs default)
  (start [this]
    this)
  (stop [this]
    ;; Cleanup dependencies automatically.
    (reduce (fn [object dependency-key]
              (assoc object dependency-key nil))
            this
            (-> this component/dependencies keys))))
```

As I understand it, this implementation is safe because components are required to be associative, and that no type information is lost in the case of records.

Let me know what you think and if I am overlooking some issue. I will open a PR in case of a positive feedback.

**Comment by stuartsierra** [comment]
Hi @mthl, thanks for your interest in Component!

The choice not to remove dependencies in the `stop` method was deliberate for a couple of reasons:

1. A stopped system may still hold references that are useful for debugging.

2. There may be a difference between starting a system the first time and *re*-starting it after it has been started and stopped. For example, the `start` method may be able to reuse parts of the system that were started before, such as cached values. This is not a common use for Components, but I want to leave the option available.

There isn't really any need to remove the references to dependent components. They are still part of the system map, so they have the same lifespan as the system. If you call `start` on the system again, it will just re-assoc the dependencies, replacing the old ones.

Hope this is helpful context, thanks again for your submission.
–S

**Comment by mthl** [comment]
Hello @stuartsierra ,

Thanks for explaining the reasons justifying this design decision.
